<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>d0f7ef31-3003-4104-a7af-99b6ecae4324</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspire.ApiService\Aspire.ApiService.csproj" />
    <ProjectReference Include="..\Aspire.Web\Aspire.Web.csproj" />
  </ItemGroup>

</Project>
